[[work]]
number = 37
image_url = ""
title = "Terminal Ave."
year_created = "2024"
medium = "watercolor on cotton paper"
size = [11.6, 16.5]
description = ""
price = 400.00
sold = false
accepting_offer = false

[[work]]
number = 36
image_url = "https://imagedelivery.net/mKjOxek3QZwwBWUu82qeLg/f71dd2c4-f6c2-43db-d951-9e61e4e92b00/public"
title = "Alleyway in Spring"
year_created = "2024"
medium = "watercolor on cotton paper"
size = [9, 12]
description = ""
price = 400.00
sold = false
accepting_offer = false

[[work]]
number = 35
image_url = "https://imagedelivery.net/mKjOxek3QZwwBWUu82qeLg/84468a0b-26b9-464e-3b5d-aa1d686fa800/public"
title = "Virginia Corridor"
year_created = "2024"
medium = "watercolor on cotton paper"
size = [9, 12]
description = ""
price = 300.00
sold = false
accepting_offer = false

[[work]]
number = 34
image_url = "https://imagedelivery.net/mKjOxek3QZwwBWUu82qeLg/e4ebbb6f-efe8-41b0-0de8-9aeca02a2700/public"
title = "Yosemite Blvd."
year_created = "2024"
medium = "watercolor on cotton paper"
size = [9, 12]
description = ""
price = 300.00
sold = false
accepting_offer = false

[[work]]
number = 33
image_url = "https://imagedelivery.net/mKjOxek3QZwwBWUu82qeLg/fa28ee5a-7888-42a8-79a9-a43de2762d00/public"
title = "Almond Orchards"
year_created = "2024"
medium = "watercolor on cotton paper"
size = [9, 12]
description = ""
price = 300.00
sold = false
accepting_offer = false

[[work]]
number = 32
image_url = "https://imagedelivery.net/mKjOxek3QZwwBWUu82qeLg/9e833552-3334-4233-482c-9e2c6579f300/public"
title = "Woman in Alameda"
year_created = "2024"
medium = "oil on paper"
size = [9, 12]
description = ""
price = 400.00
sold = false
accepting_offer = false

[[work]]
number = 31
image_url = "https://imagedelivery.net/mKjOxek3QZwwBWUu82qeLg/dbee07cf-2973-40c6-e01a-85c1e658b500/public"
title = "Cloud Study"
year_created = "2024"
medium = "watercolor on cotton paper"
size = [4, 4]
description = ""
price = 40.00
sold = false
accepting_offer = false

[[work]]
number = 30
image_url = "https://imagedelivery.net/mKjOxek3QZwwBWUu82qeLg/904aaae7-1f56-4e46-e794-99be11ba9f00/public"
title = "Pink Sunset"
year_created = "2024"
medium = "watercolor on cotton paper"
size = [4, 4]
description = ""
price = 40.00
sold = false
accepting_offer = false

[[work]]
number = 29
image_url = "https://imagedelivery.net/mKjOxek3QZwwBWUu82qeLg/e6b39d6f-de86-4382-039b-d16eec09fc00/public"
title = "Brunnhilde"
year_created = "2024"
medium = "ink on paper"
size = [5.5, 8.5]
description = ""
price = 40.00
sold = false
accepting_offer = false

[[work]]
number = 28
image_url = "https://imagedelivery.net/mKjOxek3QZwwBWUu82qeLg/b7b4a970-a842-4702-3031-5b89167ad500/public"
title = "humans"
year_created = "2024"
medium = "ink on paper"
size = [5.5, 8.5]
description = ""
price = 40.00
sold = false
accepting_offer = false

[[work]]
number = 27
image_url = "https://imagedelivery.net/mKjOxek3QZwwBWUu82qeLg/a23304d0-8c55-4663-fc09-2fdcef2a0e00/public"
title = "US Politician"
year_created = "2024"
medium = "ink on paper"
size = [5.5, 8.5]
description = ""
price = 40.00
sold = false
accepting_offer = false

[[work]]
number = 26
image_url = "https://imagedelivery.net/mKjOxek3QZwwBWUu82qeLg/292c5a25-984d-4d7d-5168-241e7d3dd100/public"
title = "Complex"
year_created = "2024"
medium = "ink on paper"
size = [5.5, 8.5]
description = ""
price = 40.00
sold = false
accepting_offer = false

[[work]]
number = 25
image_url = "https://imagedelivery.net/mKjOxek3QZwwBWUu82qeLg/24bfb852-5d16-4a6a-9fc5-ce5145085100/public"
title = "Night Mask"
year_created = "2024"
medium = "gouache on paper"
size = [5, 5]
description = ""
price = 80.00
sold = false
accepting_offer = false

[[work]]
number = 24
image_url = "https://imagedelivery.net/mKjOxek3QZwwBWUu82qeLg/c65b1ea1-e795-46fb-d21c-009b68773b00/public"
title = "San Diego"
year_created = "2024"
medium = "gouache on paper"
size = [5, 5]
description = ""
price = 80.00
sold = false
accepting_offer = false

[[work]]
number = 23
image_url = "https://imagedelivery.net/mKjOxek3QZwwBWUu82qeLg/13ce4087-ec7b-4d9a-1863-d3423c86fa00/public"
title = "Cat"
year_created = "2024"
medium = "gouache on paper"
size = [5, 5]
description = ""
price = 60.00
sold = false
accepting_offer = false

[[work]]
number = 22
image_url = "https://imagedelivery.net/mKjOxek3QZwwBWUu82qeLg/09a0239e-8fab-48da-c377-3d70fe673c00/public"
title = "Brunette"
year_created = "2024"
medium = "oil pastel on paper"
size = [5, 6.5]
description = ""
price = 80.00
sold = false
accepting_offer = false

[[work]]
number = 21
image_url = "https://imagedelivery.net/mKjOxek3QZwwBWUu82qeLg/1458072e-f8ea-4f6f-db3d-6e2061af5100/public"
title = "Celestial Egg"
year_created = "2024"
medium = "oil pastel on paper"
size = [5, 6.6]
description = ""
price = 80.00
sold = false
accepting_offer = false

[[work]]
number = 20
image_url = "https://imagedelivery.net/mKjOxek3QZwwBWUu82qeLg/afb7ff4d-787f-463f-3466-d460393b1a00/public"
title = "Suburb from Claus Rd."
year_created = "2024"
medium = "oil pastel on paper"
size = [7, 9.5]
description = ""
price = 200.00
sold = false
accepting_offer = false

[[work]]
number = 19
image_url = "https://imagedelivery.net/mKjOxek3QZwwBWUu82qeLg/1c0cbe05-d3f6-42bd-9d2a-75595dfec400/public"
title = "Green Man"
year_created = "2024"
medium = "oil pastel on paper"
size = [9, 12]
description = ""
price = 100.00
sold = false
accepting_offer = false

[[work]]
number = 18
image_url = "https://imagedelivery.net/mKjOxek3QZwwBWUu82qeLg/2a20b46d-90d2-450f-4658-20c7f121a700/public"
title = "Frenchie"
year_created = "2023"
medium = "ink on paper"
size = [9, 12]
description = ""
price = 200.00
sold = false
accepting_offer = false

[[work]]
number = 17
image_url = ""
title = "View From an Apartment"
year_created = "2023"
medium = "ink on paper"
size = [9, 12]
description = ""
price = 100.00
sold = false
accepting_offer = false

[[work]]
number = 16
image_url = "https://imagedelivery.net/mKjOxek3QZwwBWUu82qeLg/e524dbc7-a4b6-4961-df44-b8d30e856500/public"
title = "Tome"
year_created = "2021"
medium = "ink on paper"
size = [9, 12]
description = ""
price = 100.00
sold = false
accepting_offer = false

[[work]]
number = 15
image_url = "https://imagedelivery.net/mKjOxek3QZwwBWUu82qeLg/3a6984f4-5c66-4202-30aa-40f61430e900/public"
title = "Assent"
year_created = "2021"
medium = "ink on paper"
size = [9, 12]
description = ""
price = 100.00
sold = false
accepting_offer = false

[[work]]
number = 14
image_url = ""
title = "Reveal"
year_created = "2021"
medium = "ink on paper"
size = [9, 12]
description = ""
price = 100.00
sold = false
accepting_offer = false

[[work]]
number = 13
image_url = "https://imagedelivery.net/mKjOxek3QZwwBWUu82qeLg/e16dab98-19a9-4a1b-84c2-d1bdca653b00/public"
title = "The Musician"
year_created = "2021"
medium = "ink on paper"
size = [9, 12]
description = ""
price = 100.00
sold = false
accepting_offer = false

[[work]]
number = 12
image_url = "https://imagedelivery.net/mKjOxek3QZwwBWUu82qeLg/3c86bebb-e4fa-4893-61f5-e690d8993700/public"
title = "Bliss"
year_created = "2021"
medium = "ink on paper"
size = [9, 12]
description = ""
price = 100.00
sold = false
accepting_offer = false

[[work]]
number = 11
image_url = "https://imagedelivery.net/mKjOxek3QZwwBWUu82qeLg/ad975e2a-b29b-493e-6804-397552ad4600/public"
title = "eternal"
year_created = "c. 201-"
medium = "marker on paper"
size = [9, 12]
description = ""
price = 100.00
sold = false
accepting_offer = false

[[work]]
number = 10
image_url = "https://imagedelivery.net/mKjOxek3QZwwBWUu82qeLg/a18a8483-5991-4253-b51a-59240321e300/public"
title = "twenty-four hours"
year_created = "c. 201-"
medium = "marker on paper"
size = [9, 12]
description = ""
price = 100.00
sold = false
accepting_offer = false

[[work]]
number = 9
image_url = "https://imagedelivery.net/mKjOxek3QZwwBWUu82qeLg/966636c9-b5a9-4f77-ad9a-663fe3fecc00/public"
title = "conversation"
year_created = "c. 201-"
medium = "marker on paper"
size = [9, 12]
description = ""
price = 100.00
sold = false
accepting_offer = false

[[work]]
number = 8
image_url = "https://imagedelivery.net/mKjOxek3QZwwBWUu82qeLg/8ccc56b3-3717-4e7c-43bc-a57c9df9d800/public"
title = "happiness"
year_created = "c. 201-"
medium = "marker on paper"
size = [9, 12]
description = ""
price = 100.00
sold = false
accepting_offer = false

[[work]]
number = 7
image_url = "https://imagedelivery.net/mKjOxek3QZwwBWUu82qeLg/fdf1c1f2-73a5-4f5b-7dd3-b8e4a7b8c600/public"
title = "pile"
year_created = "c. 201-"
medium = "marker on paper"
size = [9, 12]
description = ""
price = 100.00
sold = false
accepting_offer = false

[[work]]
number = 6
image_url = "https://imagedelivery.net/mKjOxek3QZwwBWUu82qeLg/1f85014b-637c-4d77-cf39-40b72cf8e700/public"
title = "entertainer"
year_created = "c. 201-"
medium = "ink on paper"
size = [9, 12]
description = ""
price = 100.00
sold = false
accepting_offer = false

[[work]]
number = 5
image_url = "https://imagedelivery.net/mKjOxek3QZwwBWUu82qeLg/cfeb4893-57b5-4988-782b-e0c573931300/public"
title = "vision"
year_created = "c. 201-"
medium = "ink on paper"
size = [9, 12]
description = ""
price = 100.00
sold = false
accepting_offer = false

[[work]]
number = 4
image_url = "https://imagedelivery.net/mKjOxek3QZwwBWUu82qeLg/bfe04124-f3df-4959-9524-91fa140f0a00/public"
title = "sprite"
year_created = "c. 201-"
medium = "ink on paper"
size = [9, 12]
description = ""
price = 100.00
sold = false
accepting_offer = false

[[work]]
number = 3
image_url = "https://imagedelivery.net/mKjOxek3QZwwBWUu82qeLg/cf2d8a2c-3b9b-4051-70c2-2f001a32a800/public"
title = "stone"
year_created = "c. 201-"
medium = "ink on paper"
size = [9, 12]
description = ""
price = 100.00
sold = false
accepting_offer = false

[[work]]
number = 2
image_url = "https://imagedelivery.net/mKjOxek3QZwwBWUu82qeLg/7c317e11-4a12-4cfc-d65a-37b4c0762c00/public"
title = "specter"
year_created = "c. 201-"
medium = "ink on paper"
size = [9, 12]
description = ""
price = 100.00
sold = false
accepting_offer = false

[[work]]
number = 1
image_url = "https://imagedelivery.net/mKjOxek3QZwwBWUu82qeLg/d476552b-9613-4f5f-89ac-96f57c927200/public"
title = "passage"
year_created = "c. 201-"
medium = "ink on paper"
size = [9, 12]
description = ""
price = 100.00
sold = false
accepting_offer = false
